CREATE TABLE IF NOT EXISTS `TBLCustomer` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FirstName` varchar(255) NOT NULL,
  `LastName` varchar(255) NOT NULL,
  `StreetNo` varchar(10) DEFAULT NULL,
  `StreetName` varchar(255) DEFAULT NULL,
  `City` varchar(255) DEFAULT NULL,
  `States` int(11) DEFAULT NULL,
  `Zip` int(11) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `SSN` char(9) DEFAULT NULL,
  `PhoneNumber` char(10) DEFAULT NULL,
  `CellPhoneNumber` char(10) DEFAULT NULL,
  `EmailAddress` varchar(255) NOT NULL,
  `UserPassword` varchar(255) NOT NULL,
  `Gender` int(11) DEFAULT NULL,
  `Race` int(11) DEFAULT NULL,
  `EmploymentStatus` int(11) DEFAULT NULL,
  `Income` int(11) DEFAULT NULL,
  `HealthCareCoverageType` int(11) DEFAULT NULL,
  `DentalCareCoverageType` int(11) DEFAULT NULL,
  `PlanType` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_Gender` (`Gender`),
  KEY `FK_EmploymentStatus` (`EmploymentStatus`),
  KEY `FK_Race` (`Race`),
  KEY `FK_State` (`States`),
  KEY `FK_PlanType` (`PlanType`),
  KEY `FK_DentalCare` (`DentalCareCoverageType`),
  KEY `FK_HealthCare` (`HealthCareCoverageType`),
  KEY `FK_Income` (`Income`),
  CONSTRAINT `FK_Income` FOREIGN KEY (`Income`) REFERENCES `TBLIncome` (`IncomeID`),
  CONSTRAINT `FK_DentalCare` FOREIGN KEY (`DentalCareCoverageType`) REFERENCES `TBLDentalCareCoverage` (`DentalID`),
  CONSTRAINT `FK_EmploymentStatus` FOREIGN KEY (`EmploymentStatus`) REFERENCES `TBLEmploymentStatus` (`EmploymentID`),
  CONSTRAINT `FK_Gender` FOREIGN KEY (`Gender`) REFERENCES `TBLGender` (`GenderID`),
  CONSTRAINT `FK_HealthCare` FOREIGN KEY (`HealthCareCoverageType`) REFERENCES `TBLHealthCareCoverage` (`HealthID`),
  CONSTRAINT `FK_PlanType` FOREIGN KEY (`PlanType`) REFERENCES `TBLInsurancePlans` (`PlanID`),
  CONSTRAINT `FK_Race` FOREIGN KEY (`Race`) REFERENCES `TBLRace` (`RaceID`),
  CONSTRAINT `FK_State` FOREIGN KEY (`States`) REFERENCES `TBLStatesZips` (`StateID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;