CREATE TABLE 'TBLProfile' (
  'user_id' int(11) NOT NULL AUTO_INCREMENT,
  'ssn' varchar(256) DEFAULT NULL,
  'dob' timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  'customer_type_id' int(11) DEFAULT NULL,
  'plan_id' int(11) DEFAULT NULL,
  'retired' int(11) DEFAULT NULL,
  'special_needs' int(11) DEFAULT NULL,
  'supplemental' int(11) DEFAULT NULL,
  'family_plan' int(11) DEFAULT NULL,
  'student' int(11) DEFAULT NULL,
  'young_adult' int(11) DEFAULT NULL,
  'gender_id' int(11) DEFAULT NULL,
  PRIMARY KEY ('user_id'),
  KEY 'fk_gender' ('gender_id'),
  KEY 'fk_customer_type' ('customer_type_id'),
  KEY 'fk_plan_profile' ('plan_id'),
  CONSTRAINT 'fk_customer_type' FOREIGN KEY ('customer_type_id') REFERENCES 'TBLCustomerType' ('customer_type_id'),
  CONSTRAINT 'fk_gender' FOREIGN KEY ('gender_id') REFERENCES 'TBLGender' ('gender_id'),
  CONSTRAINT 'fk_plan' FOREIGN KEY ('plan_id') REFERENCES 'TBLInsurancePlan' ('plan_id'),
  CONSTRAINT 'fk_plan_profile' FOREIGN KEY ('plan_id') REFERENCES 'TBLInsurancePlan' ('plan_id')
) ENGINE=InnoDB DEFAULT CHARSET=latin1;